# Generated by Django 5.0.1 on 2024-05-28 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameGroup', models.CharField(verbose_name='Группа')),
                ('Year', models.CharField(verbose_name='Год')),
                ('classification', models.CharField(verbose_name='Класификация')),
                ('SpecializationGroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.specialization', verbose_name='Cпециальность')),
            ],
        ),
        migrations.CreateModel(
            name='Discip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField()),
                ('Name', models.CharField()),
                ('types_work', models.CharField(blank=True, null=True, verbose_name='Тип работы')),
                ('Times_files', models.DateField(blank=True, null=True, verbose_name='Дата сдача работ')),
                ('chapter', models.CharField()),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Group.groupuniversity')),
            ],
        ),
    ]
