# Generated by Django 5.0.1 on 2024-05-28 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameFaculty', models.CharField(max_length=255, verbose_name='Название кафедры')),
                ('FacultyLoginPasswords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.loginfaculty')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Specialization', models.CharField(max_length=250, verbose_name='Название специальности')),
                ('Code_Specialization', models.CharField(max_length=250, verbose_name='Код специальности')),
                ('SpecializationFaculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.facultyuniversity', verbose_name='Специализация кафедры')),
            ],
        ),
    ]
