# Generated by Django 5.0.1 on 2024-05-28 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Group', '0001_initial'),
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_name', models.CharField(max_length=255, verbose_name='Фамилия студента')),
                ('First_name', models.CharField(max_length=255, verbose_name='Имя студента')),
                ('Middle_name', models.CharField(max_length=255, verbose_name='Отчество студента')),
                ('EmailStudents', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Почта студента')),
                ('GroupStudents', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Group.groupuniversity', verbose_name='Студент группы')),
                ('StudentLoginPasswords', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.loginstudents', verbose_name='Авторизация Студента')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студентов',
                'db_table': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(null=True)),
                ('Course', models.CharField(null=True)),
                ('Name_themes', models.CharField(null=True)),
                ('Files', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Работы')),
                ('statuc', models.BooleanField(default=False)),
                ('DiscipId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Group.discip')),
                ('StudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'db_table': 'Темы',
            },
        ),
    ]
