# Generated by Django 5.0.1 on 2024-05-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='Type',
            new_name='Types_work',
        ),
    ]
