# Generated by Django 5.0.1 on 2024-04-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login_faculty', models.CharField(max_length=250)),
                ('Password_faculty', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Авторизация кафедры',
                'verbose_name_plural': 'Авторизация кафедры',
                'db_table': 'Авторизация кафедры',
            },
        ),
        migrations.CreateModel(
            name='LoginStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login_Student', models.CharField(max_length=250)),
                ('Password_Student', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Авторизация студента',
                'verbose_name_plural': 'Авторизация студента',
                'db_table': 'Авторизация студента',
            },
        ),
    ]
